local opt = vim.opt
local g = vim.g

g.mapleader = " "
g.maplocalleader = " "

opt.autochdir = false
opt.backup = false
opt.clipboard = "unnamedplus"
opt.completeopt = { "menu", "menuone", "noselect" }
opt.cursorline = true
opt.expandtab = true
opt.fileencoding = "utf-8"
opt.hidden = true
opt.hlsearch = true
opt.ignorecase = true
opt.incsearch = true
opt.guifont = "JetBrainsMono Nerd Font:h14"
opt.mouse = "a"
opt.number = true
opt.relativenumber = true
opt.scrolloff = 8
opt.shiftround = true
opt.shiftwidth = 2
opt.showmode = false
opt.sidescrolloff = 8
opt.signcolumn = "yes"
opt.smartcase = true
opt.smartindent = true
opt.splitbelow = true
opt.splitright = true
opt.swapfile = false
opt.tabstop = 2
opt.termguicolors = true
opt.timeout = true
opt.timeoutlen = 400
opt.undofile = true
opt.updatetime = 200
opt.wrap = false
opt.winblend = 15
opt.pumblend = 10
opt.fillchars = {
  eob = " ",
  fold = " ",
  diff = "╱",
  vert = "▏",
}
